
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

globalThis['__dirname'] = '/'

import * as runtime from "@prisma/client/runtime/wasm-compiler-edge"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model User
 * A second client built for Cloudflare Workers.
 * 
 * The default client decodes its WASM query compiler from base64 and calls
 * `new WebAssembly.Module(bytes)`, which workerd forbids — every query throws
 * "Wasm code generation disallowed by embedder". The workerd runtime imports
 * the wasm as a module instead, so the platform compiles it at deploy time.
 * Node keeps using the client above, because that module import does not
 * resolve under tsx.
 */
export type User = Prisma.UserModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Verification
 * 
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Passkey
 * 
 */
export type Passkey = Prisma.PasskeyModel
/**
 * Model TwoFactor
 * 
 */
export type TwoFactor = Prisma.TwoFactorModel
/**
 * Model Organization
 * 
 */
export type Organization = Prisma.OrganizationModel
/**
 * Model Member
 * 
 */
export type Member = Prisma.MemberModel
/**
 * Model Invitation
 * 
 */
export type Invitation = Prisma.InvitationModel
/**
 * Model Purchase
 * 
 */
export type Purchase = Prisma.PurchaseModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Collection
 * A cross-department merchandising grouping: "what do I want to do",
 * as opposed to Category, which answers "what kind of thing is it".
 * A product sits in exactly one Category but any number of Collections.
 */
export type Collection = Prisma.CollectionModel
/**
 * Model ProductCollection
 * 
 */
export type ProductCollection = Prisma.ProductCollectionModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model ProductImage
 * 
 */
export type ProductImage = Prisma.ProductImageModel
/**
 * Model ProductVariant
 * 
 */
export type ProductVariant = Prisma.ProductVariantModel
/**
 * Model Address
 * 
 */
export type Address = Prisma.AddressModel
/**
 * Model Order
 * 
 */
export type Order = Prisma.OrderModel
/**
 * Model OrderItem
 * 
 */
export type OrderItem = Prisma.OrderItemModel
/**
 * Model Review
 * 
 */
export type Review = Prisma.ReviewModel
/**
 * Model StoreTransaction
 * 
 */
export type StoreTransaction = Prisma.StoreTransactionModel
/**
 * Model WebhookEvent
 * 
 */
export type WebhookEvent = Prisma.WebhookEventModel
/**
 * Model OrderStatusEvent
 * 
 */
export type OrderStatusEvent = Prisma.OrderStatusEventModel
/**
 * Model InventoryEvent
 * 
 */
export type InventoryEvent = Prisma.InventoryEventModel
/**
 * Model RateLimit
 * Better Auth's rate-limit counters.
 * 
 * The default "memory" storage keeps a Map per process, which on Workers means
 * a counter per isolate: the effective limit becomes the configured max times
 * however many isolates happen to be warm, and it resets whenever one is
 * evicted. Database storage is the only shared counter available to us without
 * adding Redis.
 * 
 * `lastRequest` is epoch milliseconds, stored as BigInt because it exceeds the
 * range of a 32-bit Int.
 */
export type RateLimit = Prisma.RateLimitModel
/**
 * Model LandingSection
 * One band of the marketing landing page.
 * 
 * The catalogue of section types lives in code (`@repo/commerce/landing`),
 * because each one is a React component with its own shape. A row here
 * records what an editor decided about a section: whether it shows, where it
 * sits, and any copy that overrides the built-in default.
 * 
 * `settings` holds only the fields an editor actually changed. An absent or
 * empty field falls back to the shipped default, so a half-filled row can
 * never blank out a band of the page.
 */
export type LandingSection = Prisma.LandingSectionModel
