
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const PurchaseType = {
  SUBSCRIPTION: 'SUBSCRIPTION',
  ONE_TIME: 'ONE_TIME'
} as const

export type PurchaseType = (typeof PurchaseType)[keyof typeof PurchaseType]


export const ProductStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED'
} as const

export type ProductStatus = (typeof ProductStatus)[keyof typeof ProductStatus]


export const OrderStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  READY_FOR_DELIVERY: 'READY_FOR_DELIVERY',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]


export const StorePaymentStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
} as const

export type StorePaymentStatus = (typeof StorePaymentStatus)[keyof typeof StorePaymentStatus]


export const StorePaymentMethod = {
  MOCK: 'MOCK',
  ONLINE: 'ONLINE',
  CARD: 'CARD',
  MOBILE_MONEY: 'MOBILE_MONEY',
  CASH_ON_DELIVERY: 'CASH_ON_DELIVERY'
} as const

export type StorePaymentMethod = (typeof StorePaymentMethod)[keyof typeof StorePaymentMethod]


export const InventoryEventType = {
  RESTOCK: 'RESTOCK',
  ADJUSTMENT: 'ADJUSTMENT',
  SALE: 'SALE',
  RETURN: 'RETURN'
} as const

export type InventoryEventType = (typeof InventoryEventType)[keyof typeof InventoryEventType]
