
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StoreTransaction` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/wasm-compiler-edge"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StoreTransaction
 * 
 */
export type StoreTransactionModel = runtime.Types.Result.DefaultSelection<Prisma.$StoreTransactionPayload>

export type AggregateStoreTransaction = {
  _count: StoreTransactionCountAggregateOutputType | null
  _avg: StoreTransactionAvgAggregateOutputType | null
  _sum: StoreTransactionSumAggregateOutputType | null
  _min: StoreTransactionMinAggregateOutputType | null
  _max: StoreTransactionMaxAggregateOutputType | null
}

export type StoreTransactionAvgAggregateOutputType = {
  amountInPesewas: number | null
}

export type StoreTransactionSumAggregateOutputType = {
  amountInPesewas: number | null
}

export type StoreTransactionMinAggregateOutputType = {
  id: string | null
  orderId: string | null
  reference: string | null
  provider: string | null
  paymentMethod: $Enums.StorePaymentMethod | null
  status: $Enums.StorePaymentStatus | null
  amountInPesewas: number | null
  currency: string | null
  providerPaymentId: string | null
  processedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StoreTransactionMaxAggregateOutputType = {
  id: string | null
  orderId: string | null
  reference: string | null
  provider: string | null
  paymentMethod: $Enums.StorePaymentMethod | null
  status: $Enums.StorePaymentStatus | null
  amountInPesewas: number | null
  currency: string | null
  providerPaymentId: string | null
  processedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StoreTransactionCountAggregateOutputType = {
  id: number
  orderId: number
  reference: number
  provider: number
  paymentMethod: number
  status: number
  amountInPesewas: number
  currency: number
  providerPaymentId: number
  providerPayload: number
  processedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type StoreTransactionAvgAggregateInputType = {
  amountInPesewas?: true
}

export type StoreTransactionSumAggregateInputType = {
  amountInPesewas?: true
}

export type StoreTransactionMinAggregateInputType = {
  id?: true
  orderId?: true
  reference?: true
  provider?: true
  paymentMethod?: true
  status?: true
  amountInPesewas?: true
  currency?: true
  providerPaymentId?: true
  processedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type StoreTransactionMaxAggregateInputType = {
  id?: true
  orderId?: true
  reference?: true
  provider?: true
  paymentMethod?: true
  status?: true
  amountInPesewas?: true
  currency?: true
  providerPaymentId?: true
  processedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type StoreTransactionCountAggregateInputType = {
  id?: true
  orderId?: true
  reference?: true
  provider?: true
  paymentMethod?: true
  status?: true
  amountInPesewas?: true
  currency?: true
  providerPaymentId?: true
  providerPayload?: true
  processedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type StoreTransactionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StoreTransaction to aggregate.
   */
  where?: Prisma.StoreTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoreTransactions to fetch.
   */
  orderBy?: Prisma.StoreTransactionOrderByWithRelationInput | Prisma.StoreTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StoreTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoreTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoreTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StoreTransactions
  **/
  _count?: true | StoreTransactionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StoreTransactionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StoreTransactionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StoreTransactionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StoreTransactionMaxAggregateInputType
}

export type GetStoreTransactionAggregateType<T extends StoreTransactionAggregateArgs> = {
      [P in keyof T & keyof AggregateStoreTransaction]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStoreTransaction[P]>
    : Prisma.GetScalarType<T[P], AggregateStoreTransaction[P]>
}




export type StoreTransactionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StoreTransactionWhereInput
  orderBy?: Prisma.StoreTransactionOrderByWithAggregationInput | Prisma.StoreTransactionOrderByWithAggregationInput[]
  by: Prisma.StoreTransactionScalarFieldEnum[] | Prisma.StoreTransactionScalarFieldEnum
  having?: Prisma.StoreTransactionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StoreTransactionCountAggregateInputType | true
  _avg?: StoreTransactionAvgAggregateInputType
  _sum?: StoreTransactionSumAggregateInputType
  _min?: StoreTransactionMinAggregateInputType
  _max?: StoreTransactionMaxAggregateInputType
}

export type StoreTransactionGroupByOutputType = {
  id: string
  orderId: string
  reference: string
  provider: string
  paymentMethod: $Enums.StorePaymentMethod
  status: $Enums.StorePaymentStatus
  amountInPesewas: number
  currency: string
  providerPaymentId: string | null
  providerPayload: runtime.JsonValue | null
  processedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: StoreTransactionCountAggregateOutputType | null
  _avg: StoreTransactionAvgAggregateOutputType | null
  _sum: StoreTransactionSumAggregateOutputType | null
  _min: StoreTransactionMinAggregateOutputType | null
  _max: StoreTransactionMaxAggregateOutputType | null
}

type GetStoreTransactionGroupByPayload<T extends StoreTransactionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StoreTransactionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StoreTransactionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StoreTransactionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StoreTransactionGroupByOutputType[P]>
      }
    >
  >



export type StoreTransactionWhereInput = {
  AND?: Prisma.StoreTransactionWhereInput | Prisma.StoreTransactionWhereInput[]
  OR?: Prisma.StoreTransactionWhereInput[]
  NOT?: Prisma.StoreTransactionWhereInput | Prisma.StoreTransactionWhereInput[]
  id?: Prisma.StringFilter<"StoreTransaction"> | string
  orderId?: Prisma.StringFilter<"StoreTransaction"> | string
  reference?: Prisma.StringFilter<"StoreTransaction"> | string
  provider?: Prisma.StringFilter<"StoreTransaction"> | string
  paymentMethod?: Prisma.EnumStorePaymentMethodFilter<"StoreTransaction"> | $Enums.StorePaymentMethod
  status?: Prisma.EnumStorePaymentStatusFilter<"StoreTransaction"> | $Enums.StorePaymentStatus
  amountInPesewas?: Prisma.IntFilter<"StoreTransaction"> | number
  currency?: Prisma.StringFilter<"StoreTransaction"> | string
  providerPaymentId?: Prisma.StringNullableFilter<"StoreTransaction"> | string | null
  providerPayload?: Prisma.JsonNullableFilter<"StoreTransaction">
  processedAt?: Prisma.DateTimeNullableFilter<"StoreTransaction"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"StoreTransaction"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StoreTransaction"> | Date | string
  order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
}

export type StoreTransactionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  reference?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amountInPesewas?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  providerPaymentId?: Prisma.SortOrderInput | Prisma.SortOrder
  providerPayload?: Prisma.SortOrderInput | Prisma.SortOrder
  processedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  order?: Prisma.OrderOrderByWithRelationInput
}

export type StoreTransactionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  reference?: string
  AND?: Prisma.StoreTransactionWhereInput | Prisma.StoreTransactionWhereInput[]
  OR?: Prisma.StoreTransactionWhereInput[]
  NOT?: Prisma.StoreTransactionWhereInput | Prisma.StoreTransactionWhereInput[]
  orderId?: Prisma.StringFilter<"StoreTransaction"> | string
  provider?: Prisma.StringFilter<"StoreTransaction"> | string
  paymentMethod?: Prisma.EnumStorePaymentMethodFilter<"StoreTransaction"> | $Enums.StorePaymentMethod
  status?: Prisma.EnumStorePaymentStatusFilter<"StoreTransaction"> | $Enums.StorePaymentStatus
  amountInPesewas?: Prisma.IntFilter<"StoreTransaction"> | number
  currency?: Prisma.StringFilter<"StoreTransaction"> | string
  providerPaymentId?: Prisma.StringNullableFilter<"StoreTransaction"> | string | null
  providerPayload?: Prisma.JsonNullableFilter<"StoreTransaction">
  processedAt?: Prisma.DateTimeNullableFilter<"StoreTransaction"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"StoreTransaction"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StoreTransaction"> | Date | string
  order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
}, "id" | "reference">

export type StoreTransactionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  reference?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amountInPesewas?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  providerPaymentId?: Prisma.SortOrderInput | Prisma.SortOrder
  providerPayload?: Prisma.SortOrderInput | Prisma.SortOrder
  processedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.StoreTransactionCountOrderByAggregateInput
  _avg?: Prisma.StoreTransactionAvgOrderByAggregateInput
  _max?: Prisma.StoreTransactionMaxOrderByAggregateInput
  _min?: Prisma.StoreTransactionMinOrderByAggregateInput
  _sum?: Prisma.StoreTransactionSumOrderByAggregateInput
}

export type StoreTransactionScalarWhereWithAggregatesInput = {
  AND?: Prisma.StoreTransactionScalarWhereWithAggregatesInput | Prisma.StoreTransactionScalarWhereWithAggregatesInput[]
  OR?: Prisma.StoreTransactionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StoreTransactionScalarWhereWithAggregatesInput | Prisma.StoreTransactionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"StoreTransaction"> | string
  orderId?: Prisma.StringWithAggregatesFilter<"StoreTransaction"> | string
  reference?: Prisma.StringWithAggregatesFilter<"StoreTransaction"> | string
  provider?: Prisma.StringWithAggregatesFilter<"StoreTransaction"> | string
  paymentMethod?: Prisma.EnumStorePaymentMethodWithAggregatesFilter<"StoreTransaction"> | $Enums.StorePaymentMethod
  status?: Prisma.EnumStorePaymentStatusWithAggregatesFilter<"StoreTransaction"> | $Enums.StorePaymentStatus
  amountInPesewas?: Prisma.IntWithAggregatesFilter<"StoreTransaction"> | number
  currency?: Prisma.StringWithAggregatesFilter<"StoreTransaction"> | string
  providerPaymentId?: Prisma.StringNullableWithAggregatesFilter<"StoreTransaction"> | string | null
  providerPayload?: Prisma.JsonNullableWithAggregatesFilter<"StoreTransaction">
  processedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"StoreTransaction"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"StoreTransaction"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"StoreTransaction"> | Date | string
}

export type StoreTransactionCreateInput = {
  id?: string
  reference: string
  provider: string
  paymentMethod: $Enums.StorePaymentMethod
  status?: $Enums.StorePaymentStatus
  amountInPesewas: number
  currency?: string
  providerPaymentId?: string | null
  providerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  order: Prisma.OrderCreateNestedOneWithoutTransactionsInput
}

export type StoreTransactionUncheckedCreateInput = {
  id?: string
  orderId: string
  reference: string
  provider: string
  paymentMethod: $Enums.StorePaymentMethod
  status?: $Enums.StorePaymentStatus
  amountInPesewas: number
  currency?: string
  providerPaymentId?: string | null
  providerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StoreTransactionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.EnumStorePaymentMethodFieldUpdateOperationsInput | $Enums.StorePaymentMethod
  status?: Prisma.EnumStorePaymentStatusFieldUpdateOperationsInput | $Enums.StorePaymentStatus
  amountInPesewas?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  providerPaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  providerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.OrderUpdateOneRequiredWithoutTransactionsNestedInput
}

export type StoreTransactionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.EnumStorePaymentMethodFieldUpdateOperationsInput | $Enums.StorePaymentMethod
  status?: Prisma.EnumStorePaymentStatusFieldUpdateOperationsInput | $Enums.StorePaymentStatus
  amountInPesewas?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  providerPaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  providerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreTransactionCreateManyInput = {
  id?: string
  orderId: string
  reference: string
  provider: string
  paymentMethod: $Enums.StorePaymentMethod
  status?: $Enums.StorePaymentStatus
  amountInPesewas: number
  currency?: string
  providerPaymentId?: string | null
  providerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StoreTransactionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.EnumStorePaymentMethodFieldUpdateOperationsInput | $Enums.StorePaymentMethod
  status?: Prisma.EnumStorePaymentStatusFieldUpdateOperationsInput | $Enums.StorePaymentStatus
  amountInPesewas?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  providerPaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  providerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreTransactionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.EnumStorePaymentMethodFieldUpdateOperationsInput | $Enums.StorePaymentMethod
  status?: Prisma.EnumStorePaymentStatusFieldUpdateOperationsInput | $Enums.StorePaymentStatus
  amountInPesewas?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  providerPaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  providerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreTransactionListRelationFilter = {
  every?: Prisma.StoreTransactionWhereInput
  some?: Prisma.StoreTransactionWhereInput
  none?: Prisma.StoreTransactionWhereInput
}

export type StoreTransactionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StoreTransactionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  reference?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amountInPesewas?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  providerPaymentId?: Prisma.SortOrder
  providerPayload?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StoreTransactionAvgOrderByAggregateInput = {
  amountInPesewas?: Prisma.SortOrder
}

export type StoreTransactionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  reference?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amountInPesewas?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  providerPaymentId?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StoreTransactionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  reference?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amountInPesewas?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  providerPaymentId?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StoreTransactionSumOrderByAggregateInput = {
  amountInPesewas?: Prisma.SortOrder
}

export type StoreTransactionCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.StoreTransactionCreateWithoutOrderInput, Prisma.StoreTransactionUncheckedCreateWithoutOrderInput> | Prisma.StoreTransactionCreateWithoutOrderInput[] | Prisma.StoreTransactionUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.StoreTransactionCreateOrConnectWithoutOrderInput | Prisma.StoreTransactionCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.StoreTransactionCreateManyOrderInputEnvelope
  connect?: Prisma.StoreTransactionWhereUniqueInput | Prisma.StoreTransactionWhereUniqueInput[]
}

export type StoreTransactionUncheckedCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.StoreTransactionCreateWithoutOrderInput, Prisma.StoreTransactionUncheckedCreateWithoutOrderInput> | Prisma.StoreTransactionCreateWithoutOrderInput[] | Prisma.StoreTransactionUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.StoreTransactionCreateOrConnectWithoutOrderInput | Prisma.StoreTransactionCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.StoreTransactionCreateManyOrderInputEnvelope
  connect?: Prisma.StoreTransactionWhereUniqueInput | Prisma.StoreTransactionWhereUniqueInput[]
}

export type StoreTransactionUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.StoreTransactionCreateWithoutOrderInput, Prisma.StoreTransactionUncheckedCreateWithoutOrderInput> | Prisma.StoreTransactionCreateWithoutOrderInput[] | Prisma.StoreTransactionUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.StoreTransactionCreateOrConnectWithoutOrderInput | Prisma.StoreTransactionCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.StoreTransactionUpsertWithWhereUniqueWithoutOrderInput | Prisma.StoreTransactionUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.StoreTransactionCreateManyOrderInputEnvelope
  set?: Prisma.StoreTransactionWhereUniqueInput | Prisma.StoreTransactionWhereUniqueInput[]
  disconnect?: Prisma.StoreTransactionWhereUniqueInput | Prisma.StoreTransactionWhereUniqueInput[]
  delete?: Prisma.StoreTransactionWhereUniqueInput | Prisma.StoreTransactionWhereUniqueInput[]
  connect?: Prisma.StoreTransactionWhereUniqueInput | Prisma.StoreTransactionWhereUniqueInput[]
  update?: Prisma.StoreTransactionUpdateWithWhereUniqueWithoutOrderInput | Prisma.StoreTransactionUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.StoreTransactionUpdateManyWithWhereWithoutOrderInput | Prisma.StoreTransactionUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.StoreTransactionScalarWhereInput | Prisma.StoreTransactionScalarWhereInput[]
}

export type StoreTransactionUncheckedUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.StoreTransactionCreateWithoutOrderInput, Prisma.StoreTransactionUncheckedCreateWithoutOrderInput> | Prisma.StoreTransactionCreateWithoutOrderInput[] | Prisma.StoreTransactionUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.StoreTransactionCreateOrConnectWithoutOrderInput | Prisma.StoreTransactionCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.StoreTransactionUpsertWithWhereUniqueWithoutOrderInput | Prisma.StoreTransactionUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.StoreTransactionCreateManyOrderInputEnvelope
  set?: Prisma.StoreTransactionWhereUniqueInput | Prisma.StoreTransactionWhereUniqueInput[]
  disconnect?: Prisma.StoreTransactionWhereUniqueInput | Prisma.StoreTransactionWhereUniqueInput[]
  delete?: Prisma.StoreTransactionWhereUniqueInput | Prisma.StoreTransactionWhereUniqueInput[]
  connect?: Prisma.StoreTransactionWhereUniqueInput | Prisma.StoreTransactionWhereUniqueInput[]
  update?: Prisma.StoreTransactionUpdateWithWhereUniqueWithoutOrderInput | Prisma.StoreTransactionUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.StoreTransactionUpdateManyWithWhereWithoutOrderInput | Prisma.StoreTransactionUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.StoreTransactionScalarWhereInput | Prisma.StoreTransactionScalarWhereInput[]
}

export type StoreTransactionCreateWithoutOrderInput = {
  id?: string
  reference: string
  provider: string
  paymentMethod: $Enums.StorePaymentMethod
  status?: $Enums.StorePaymentStatus
  amountInPesewas: number
  currency?: string
  providerPaymentId?: string | null
  providerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StoreTransactionUncheckedCreateWithoutOrderInput = {
  id?: string
  reference: string
  provider: string
  paymentMethod: $Enums.StorePaymentMethod
  status?: $Enums.StorePaymentStatus
  amountInPesewas: number
  currency?: string
  providerPaymentId?: string | null
  providerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StoreTransactionCreateOrConnectWithoutOrderInput = {
  where: Prisma.StoreTransactionWhereUniqueInput
  create: Prisma.XOR<Prisma.StoreTransactionCreateWithoutOrderInput, Prisma.StoreTransactionUncheckedCreateWithoutOrderInput>
}

export type StoreTransactionCreateManyOrderInputEnvelope = {
  data: Prisma.StoreTransactionCreateManyOrderInput | Prisma.StoreTransactionCreateManyOrderInput[]
}

export type StoreTransactionUpsertWithWhereUniqueWithoutOrderInput = {
  where: Prisma.StoreTransactionWhereUniqueInput
  update: Prisma.XOR<Prisma.StoreTransactionUpdateWithoutOrderInput, Prisma.StoreTransactionUncheckedUpdateWithoutOrderInput>
  create: Prisma.XOR<Prisma.StoreTransactionCreateWithoutOrderInput, Prisma.StoreTransactionUncheckedCreateWithoutOrderInput>
}

export type StoreTransactionUpdateWithWhereUniqueWithoutOrderInput = {
  where: Prisma.StoreTransactionWhereUniqueInput
  data: Prisma.XOR<Prisma.StoreTransactionUpdateWithoutOrderInput, Prisma.StoreTransactionUncheckedUpdateWithoutOrderInput>
}

export type StoreTransactionUpdateManyWithWhereWithoutOrderInput = {
  where: Prisma.StoreTransactionScalarWhereInput
  data: Prisma.XOR<Prisma.StoreTransactionUpdateManyMutationInput, Prisma.StoreTransactionUncheckedUpdateManyWithoutOrderInput>
}

export type StoreTransactionScalarWhereInput = {
  AND?: Prisma.StoreTransactionScalarWhereInput | Prisma.StoreTransactionScalarWhereInput[]
  OR?: Prisma.StoreTransactionScalarWhereInput[]
  NOT?: Prisma.StoreTransactionScalarWhereInput | Prisma.StoreTransactionScalarWhereInput[]
  id?: Prisma.StringFilter<"StoreTransaction"> | string
  orderId?: Prisma.StringFilter<"StoreTransaction"> | string
  reference?: Prisma.StringFilter<"StoreTransaction"> | string
  provider?: Prisma.StringFilter<"StoreTransaction"> | string
  paymentMethod?: Prisma.EnumStorePaymentMethodFilter<"StoreTransaction"> | $Enums.StorePaymentMethod
  status?: Prisma.EnumStorePaymentStatusFilter<"StoreTransaction"> | $Enums.StorePaymentStatus
  amountInPesewas?: Prisma.IntFilter<"StoreTransaction"> | number
  currency?: Prisma.StringFilter<"StoreTransaction"> | string
  providerPaymentId?: Prisma.StringNullableFilter<"StoreTransaction"> | string | null
  providerPayload?: Prisma.JsonNullableFilter<"StoreTransaction">
  processedAt?: Prisma.DateTimeNullableFilter<"StoreTransaction"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"StoreTransaction"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StoreTransaction"> | Date | string
}

export type StoreTransactionCreateManyOrderInput = {
  id?: string
  reference: string
  provider: string
  paymentMethod: $Enums.StorePaymentMethod
  status?: $Enums.StorePaymentStatus
  amountInPesewas: number
  currency?: string
  providerPaymentId?: string | null
  providerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StoreTransactionUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.EnumStorePaymentMethodFieldUpdateOperationsInput | $Enums.StorePaymentMethod
  status?: Prisma.EnumStorePaymentStatusFieldUpdateOperationsInput | $Enums.StorePaymentStatus
  amountInPesewas?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  providerPaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  providerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreTransactionUncheckedUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.EnumStorePaymentMethodFieldUpdateOperationsInput | $Enums.StorePaymentMethod
  status?: Prisma.EnumStorePaymentStatusFieldUpdateOperationsInput | $Enums.StorePaymentStatus
  amountInPesewas?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  providerPaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  providerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreTransactionUncheckedUpdateManyWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.EnumStorePaymentMethodFieldUpdateOperationsInput | $Enums.StorePaymentMethod
  status?: Prisma.EnumStorePaymentStatusFieldUpdateOperationsInput | $Enums.StorePaymentStatus
  amountInPesewas?: Prisma.IntFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  providerPaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  providerPayload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type StoreTransactionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  reference?: boolean
  provider?: boolean
  paymentMethod?: boolean
  status?: boolean
  amountInPesewas?: boolean
  currency?: boolean
  providerPaymentId?: boolean
  providerPayload?: boolean
  processedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["storeTransaction"]>

export type StoreTransactionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  reference?: boolean
  provider?: boolean
  paymentMethod?: boolean
  status?: boolean
  amountInPesewas?: boolean
  currency?: boolean
  providerPaymentId?: boolean
  providerPayload?: boolean
  processedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["storeTransaction"]>

export type StoreTransactionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  reference?: boolean
  provider?: boolean
  paymentMethod?: boolean
  status?: boolean
  amountInPesewas?: boolean
  currency?: boolean
  providerPaymentId?: boolean
  providerPayload?: boolean
  processedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["storeTransaction"]>

export type StoreTransactionSelectScalar = {
  id?: boolean
  orderId?: boolean
  reference?: boolean
  provider?: boolean
  paymentMethod?: boolean
  status?: boolean
  amountInPesewas?: boolean
  currency?: boolean
  providerPaymentId?: boolean
  providerPayload?: boolean
  processedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type StoreTransactionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "orderId" | "reference" | "provider" | "paymentMethod" | "status" | "amountInPesewas" | "currency" | "providerPaymentId" | "providerPayload" | "processedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["storeTransaction"]>
export type StoreTransactionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}
export type StoreTransactionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}
export type StoreTransactionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}

export type $StoreTransactionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StoreTransaction"
  objects: {
    order: Prisma.$OrderPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    orderId: string
    reference: string
    provider: string
    paymentMethod: $Enums.StorePaymentMethod
    status: $Enums.StorePaymentStatus
    amountInPesewas: number
    currency: string
    providerPaymentId: string | null
    providerPayload: runtime.JsonValue | null
    processedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["storeTransaction"]>
  composites: {}
}

export type StoreTransactionGetPayload<S extends boolean | null | undefined | StoreTransactionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StoreTransactionPayload, S>

export type StoreTransactionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StoreTransactionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StoreTransactionCountAggregateInputType | true
  }

export interface StoreTransactionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StoreTransaction'], meta: { name: 'StoreTransaction' } }
  /**
   * Find zero or one StoreTransaction that matches the filter.
   * @param {StoreTransactionFindUniqueArgs} args - Arguments to find a StoreTransaction
   * @example
   * // Get one StoreTransaction
   * const storeTransaction = await prisma.storeTransaction.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StoreTransactionFindUniqueArgs>(args: Prisma.SelectSubset<T, StoreTransactionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StoreTransactionClient<runtime.Types.Result.GetResult<Prisma.$StoreTransactionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StoreTransaction that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StoreTransactionFindUniqueOrThrowArgs} args - Arguments to find a StoreTransaction
   * @example
   * // Get one StoreTransaction
   * const storeTransaction = await prisma.storeTransaction.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StoreTransactionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StoreTransactionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StoreTransactionClient<runtime.Types.Result.GetResult<Prisma.$StoreTransactionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StoreTransaction that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreTransactionFindFirstArgs} args - Arguments to find a StoreTransaction
   * @example
   * // Get one StoreTransaction
   * const storeTransaction = await prisma.storeTransaction.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StoreTransactionFindFirstArgs>(args?: Prisma.SelectSubset<T, StoreTransactionFindFirstArgs<ExtArgs>>): Prisma.Prisma__StoreTransactionClient<runtime.Types.Result.GetResult<Prisma.$StoreTransactionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StoreTransaction that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreTransactionFindFirstOrThrowArgs} args - Arguments to find a StoreTransaction
   * @example
   * // Get one StoreTransaction
   * const storeTransaction = await prisma.storeTransaction.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StoreTransactionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StoreTransactionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StoreTransactionClient<runtime.Types.Result.GetResult<Prisma.$StoreTransactionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StoreTransactions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreTransactionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StoreTransactions
   * const storeTransactions = await prisma.storeTransaction.findMany()
   * 
   * // Get first 10 StoreTransactions
   * const storeTransactions = await prisma.storeTransaction.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const storeTransactionWithIdOnly = await prisma.storeTransaction.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StoreTransactionFindManyArgs>(args?: Prisma.SelectSubset<T, StoreTransactionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StoreTransactionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StoreTransaction.
   * @param {StoreTransactionCreateArgs} args - Arguments to create a StoreTransaction.
   * @example
   * // Create one StoreTransaction
   * const StoreTransaction = await prisma.storeTransaction.create({
   *   data: {
   *     // ... data to create a StoreTransaction
   *   }
   * })
   * 
   */
  create<T extends StoreTransactionCreateArgs>(args: Prisma.SelectSubset<T, StoreTransactionCreateArgs<ExtArgs>>): Prisma.Prisma__StoreTransactionClient<runtime.Types.Result.GetResult<Prisma.$StoreTransactionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StoreTransactions.
   * @param {StoreTransactionCreateManyArgs} args - Arguments to create many StoreTransactions.
   * @example
   * // Create many StoreTransactions
   * const storeTransaction = await prisma.storeTransaction.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StoreTransactionCreateManyArgs>(args?: Prisma.SelectSubset<T, StoreTransactionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StoreTransactions and returns the data saved in the database.
   * @param {StoreTransactionCreateManyAndReturnArgs} args - Arguments to create many StoreTransactions.
   * @example
   * // Create many StoreTransactions
   * const storeTransaction = await prisma.storeTransaction.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StoreTransactions and only return the `id`
   * const storeTransactionWithIdOnly = await prisma.storeTransaction.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StoreTransactionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StoreTransactionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StoreTransactionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StoreTransaction.
   * @param {StoreTransactionDeleteArgs} args - Arguments to delete one StoreTransaction.
   * @example
   * // Delete one StoreTransaction
   * const StoreTransaction = await prisma.storeTransaction.delete({
   *   where: {
   *     // ... filter to delete one StoreTransaction
   *   }
   * })
   * 
   */
  delete<T extends StoreTransactionDeleteArgs>(args: Prisma.SelectSubset<T, StoreTransactionDeleteArgs<ExtArgs>>): Prisma.Prisma__StoreTransactionClient<runtime.Types.Result.GetResult<Prisma.$StoreTransactionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StoreTransaction.
   * @param {StoreTransactionUpdateArgs} args - Arguments to update one StoreTransaction.
   * @example
   * // Update one StoreTransaction
   * const storeTransaction = await prisma.storeTransaction.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StoreTransactionUpdateArgs>(args: Prisma.SelectSubset<T, StoreTransactionUpdateArgs<ExtArgs>>): Prisma.Prisma__StoreTransactionClient<runtime.Types.Result.GetResult<Prisma.$StoreTransactionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StoreTransactions.
   * @param {StoreTransactionDeleteManyArgs} args - Arguments to filter StoreTransactions to delete.
   * @example
   * // Delete a few StoreTransactions
   * const { count } = await prisma.storeTransaction.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StoreTransactionDeleteManyArgs>(args?: Prisma.SelectSubset<T, StoreTransactionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StoreTransactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreTransactionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StoreTransactions
   * const storeTransaction = await prisma.storeTransaction.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StoreTransactionUpdateManyArgs>(args: Prisma.SelectSubset<T, StoreTransactionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StoreTransactions and returns the data updated in the database.
   * @param {StoreTransactionUpdateManyAndReturnArgs} args - Arguments to update many StoreTransactions.
   * @example
   * // Update many StoreTransactions
   * const storeTransaction = await prisma.storeTransaction.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StoreTransactions and only return the `id`
   * const storeTransactionWithIdOnly = await prisma.storeTransaction.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StoreTransactionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StoreTransactionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StoreTransactionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StoreTransaction.
   * @param {StoreTransactionUpsertArgs} args - Arguments to update or create a StoreTransaction.
   * @example
   * // Update or create a StoreTransaction
   * const storeTransaction = await prisma.storeTransaction.upsert({
   *   create: {
   *     // ... data to create a StoreTransaction
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StoreTransaction we want to update
   *   }
   * })
   */
  upsert<T extends StoreTransactionUpsertArgs>(args: Prisma.SelectSubset<T, StoreTransactionUpsertArgs<ExtArgs>>): Prisma.Prisma__StoreTransactionClient<runtime.Types.Result.GetResult<Prisma.$StoreTransactionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StoreTransactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreTransactionCountArgs} args - Arguments to filter StoreTransactions to count.
   * @example
   * // Count the number of StoreTransactions
   * const count = await prisma.storeTransaction.count({
   *   where: {
   *     // ... the filter for the StoreTransactions we want to count
   *   }
   * })
  **/
  count<T extends StoreTransactionCountArgs>(
    args?: Prisma.Subset<T, StoreTransactionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StoreTransactionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StoreTransaction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreTransactionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StoreTransactionAggregateArgs>(args: Prisma.Subset<T, StoreTransactionAggregateArgs>): Prisma.PrismaPromise<GetStoreTransactionAggregateType<T>>

  /**
   * Group by StoreTransaction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreTransactionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StoreTransactionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StoreTransactionGroupByArgs['orderBy'] }
      : { orderBy?: StoreTransactionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StoreTransactionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStoreTransactionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StoreTransaction model
 */
readonly fields: StoreTransactionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StoreTransaction.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StoreTransactionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  order<T extends Prisma.OrderDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrderDefaultArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StoreTransaction model
 */
export interface StoreTransactionFieldRefs {
  readonly id: Prisma.FieldRef<"StoreTransaction", 'String'>
  readonly orderId: Prisma.FieldRef<"StoreTransaction", 'String'>
  readonly reference: Prisma.FieldRef<"StoreTransaction", 'String'>
  readonly provider: Prisma.FieldRef<"StoreTransaction", 'String'>
  readonly paymentMethod: Prisma.FieldRef<"StoreTransaction", 'StorePaymentMethod'>
  readonly status: Prisma.FieldRef<"StoreTransaction", 'StorePaymentStatus'>
  readonly amountInPesewas: Prisma.FieldRef<"StoreTransaction", 'Int'>
  readonly currency: Prisma.FieldRef<"StoreTransaction", 'String'>
  readonly providerPaymentId: Prisma.FieldRef<"StoreTransaction", 'String'>
  readonly providerPayload: Prisma.FieldRef<"StoreTransaction", 'Json'>
  readonly processedAt: Prisma.FieldRef<"StoreTransaction", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"StoreTransaction", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"StoreTransaction", 'DateTime'>
}
    

// Custom InputTypes
/**
 * StoreTransaction findUnique
 */
export type StoreTransactionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreTransaction
   */
  select?: Prisma.StoreTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreTransaction
   */
  omit?: Prisma.StoreTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreTransactionInclude<ExtArgs> | null
  /**
   * Filter, which StoreTransaction to fetch.
   */
  where: Prisma.StoreTransactionWhereUniqueInput
}

/**
 * StoreTransaction findUniqueOrThrow
 */
export type StoreTransactionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreTransaction
   */
  select?: Prisma.StoreTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreTransaction
   */
  omit?: Prisma.StoreTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreTransactionInclude<ExtArgs> | null
  /**
   * Filter, which StoreTransaction to fetch.
   */
  where: Prisma.StoreTransactionWhereUniqueInput
}

/**
 * StoreTransaction findFirst
 */
export type StoreTransactionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreTransaction
   */
  select?: Prisma.StoreTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreTransaction
   */
  omit?: Prisma.StoreTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreTransactionInclude<ExtArgs> | null
  /**
   * Filter, which StoreTransaction to fetch.
   */
  where?: Prisma.StoreTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoreTransactions to fetch.
   */
  orderBy?: Prisma.StoreTransactionOrderByWithRelationInput | Prisma.StoreTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StoreTransactions.
   */
  cursor?: Prisma.StoreTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoreTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoreTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StoreTransactions.
   */
  distinct?: Prisma.StoreTransactionScalarFieldEnum | Prisma.StoreTransactionScalarFieldEnum[]
}

/**
 * StoreTransaction findFirstOrThrow
 */
export type StoreTransactionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreTransaction
   */
  select?: Prisma.StoreTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreTransaction
   */
  omit?: Prisma.StoreTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreTransactionInclude<ExtArgs> | null
  /**
   * Filter, which StoreTransaction to fetch.
   */
  where?: Prisma.StoreTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoreTransactions to fetch.
   */
  orderBy?: Prisma.StoreTransactionOrderByWithRelationInput | Prisma.StoreTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StoreTransactions.
   */
  cursor?: Prisma.StoreTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoreTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoreTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StoreTransactions.
   */
  distinct?: Prisma.StoreTransactionScalarFieldEnum | Prisma.StoreTransactionScalarFieldEnum[]
}

/**
 * StoreTransaction findMany
 */
export type StoreTransactionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreTransaction
   */
  select?: Prisma.StoreTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreTransaction
   */
  omit?: Prisma.StoreTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreTransactionInclude<ExtArgs> | null
  /**
   * Filter, which StoreTransactions to fetch.
   */
  where?: Prisma.StoreTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoreTransactions to fetch.
   */
  orderBy?: Prisma.StoreTransactionOrderByWithRelationInput | Prisma.StoreTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StoreTransactions.
   */
  cursor?: Prisma.StoreTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoreTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoreTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StoreTransactions.
   */
  distinct?: Prisma.StoreTransactionScalarFieldEnum | Prisma.StoreTransactionScalarFieldEnum[]
}

/**
 * StoreTransaction create
 */
export type StoreTransactionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreTransaction
   */
  select?: Prisma.StoreTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreTransaction
   */
  omit?: Prisma.StoreTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreTransactionInclude<ExtArgs> | null
  /**
   * The data needed to create a StoreTransaction.
   */
  data: Prisma.XOR<Prisma.StoreTransactionCreateInput, Prisma.StoreTransactionUncheckedCreateInput>
}

/**
 * StoreTransaction createMany
 */
export type StoreTransactionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StoreTransactions.
   */
  data: Prisma.StoreTransactionCreateManyInput | Prisma.StoreTransactionCreateManyInput[]
}

/**
 * StoreTransaction createManyAndReturn
 */
export type StoreTransactionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreTransaction
   */
  select?: Prisma.StoreTransactionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StoreTransaction
   */
  omit?: Prisma.StoreTransactionOmit<ExtArgs> | null
  /**
   * The data used to create many StoreTransactions.
   */
  data: Prisma.StoreTransactionCreateManyInput | Prisma.StoreTransactionCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreTransactionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * StoreTransaction update
 */
export type StoreTransactionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreTransaction
   */
  select?: Prisma.StoreTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreTransaction
   */
  omit?: Prisma.StoreTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreTransactionInclude<ExtArgs> | null
  /**
   * The data needed to update a StoreTransaction.
   */
  data: Prisma.XOR<Prisma.StoreTransactionUpdateInput, Prisma.StoreTransactionUncheckedUpdateInput>
  /**
   * Choose, which StoreTransaction to update.
   */
  where: Prisma.StoreTransactionWhereUniqueInput
}

/**
 * StoreTransaction updateMany
 */
export type StoreTransactionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StoreTransactions.
   */
  data: Prisma.XOR<Prisma.StoreTransactionUpdateManyMutationInput, Prisma.StoreTransactionUncheckedUpdateManyInput>
  /**
   * Filter which StoreTransactions to update
   */
  where?: Prisma.StoreTransactionWhereInput
  /**
   * Limit how many StoreTransactions to update.
   */
  limit?: number
}

/**
 * StoreTransaction updateManyAndReturn
 */
export type StoreTransactionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreTransaction
   */
  select?: Prisma.StoreTransactionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StoreTransaction
   */
  omit?: Prisma.StoreTransactionOmit<ExtArgs> | null
  /**
   * The data used to update StoreTransactions.
   */
  data: Prisma.XOR<Prisma.StoreTransactionUpdateManyMutationInput, Prisma.StoreTransactionUncheckedUpdateManyInput>
  /**
   * Filter which StoreTransactions to update
   */
  where?: Prisma.StoreTransactionWhereInput
  /**
   * Limit how many StoreTransactions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreTransactionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * StoreTransaction upsert
 */
export type StoreTransactionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreTransaction
   */
  select?: Prisma.StoreTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreTransaction
   */
  omit?: Prisma.StoreTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreTransactionInclude<ExtArgs> | null
  /**
   * The filter to search for the StoreTransaction to update in case it exists.
   */
  where: Prisma.StoreTransactionWhereUniqueInput
  /**
   * In case the StoreTransaction found by the `where` argument doesn't exist, create a new StoreTransaction with this data.
   */
  create: Prisma.XOR<Prisma.StoreTransactionCreateInput, Prisma.StoreTransactionUncheckedCreateInput>
  /**
   * In case the StoreTransaction was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StoreTransactionUpdateInput, Prisma.StoreTransactionUncheckedUpdateInput>
}

/**
 * StoreTransaction delete
 */
export type StoreTransactionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreTransaction
   */
  select?: Prisma.StoreTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreTransaction
   */
  omit?: Prisma.StoreTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreTransactionInclude<ExtArgs> | null
  /**
   * Filter which StoreTransaction to delete.
   */
  where: Prisma.StoreTransactionWhereUniqueInput
}

/**
 * StoreTransaction deleteMany
 */
export type StoreTransactionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StoreTransactions to delete
   */
  where?: Prisma.StoreTransactionWhereInput
  /**
   * Limit how many StoreTransactions to delete.
   */
  limit?: number
}

/**
 * StoreTransaction without action
 */
export type StoreTransactionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreTransaction
   */
  select?: Prisma.StoreTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreTransaction
   */
  omit?: Prisma.StoreTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreTransactionInclude<ExtArgs> | null
}
